.Dd 2017-01-13
.Dt WVGAIN 1
.Os
.Sh NAME
.Nm wvgain
.Nd adds ReplayGain information to wavpack files
.Sh SYNOPSIS
.Nm wvgain
.Op Ar -options
.Ar INFILE ...
.Sh DESCRIPTION
.Nm wvgain
perceptually analyzes WavPack audio files for volume, calculates ReplayGain information based on this,
and adds the appropriate APEv2 tag fields. ReplayGain-enabled players will use this information to produce the same perceived loudness
on all tracks. Both individual track and whole album ReplayGain information can be calculated.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
album mode (all files scanned are considered an album)
.It Fl c
clean ReplayGain values from all files
.It Fl d
display calculated values only (no files are modified)
.It Fl i
ignore .wvc file (forces hybrid lossy)
.It Fl n
new files only (skip files with track info, or album info if album mode specified)
.It Fl q
quiet (keep console output to a minimum)
.It Fl s
show stored values only (no analysis)
.It Fl v
write program version to
.Pa stdout
.It Fl z[ Ns Ar n ]
don't set (n = 0 or omitted) or set (n = 1) console title to indicate progress (leaves "WvGain Completed")
.El
.Sh SEE ALSO
.Xr wavpack 1 ,
.Xr wvunpack 1 ,
.Xr wvtag 1
.Pp
Please visit www.wavpack.com for more information
.Sh COPYRIGHT
This manual page was written by Sebastian Dröge
.Aq Mt slomo@debian.org
and David Bryant
.Aq Mt david@wavpack.com .
Permission is granted to copy, distribute and/or modify this document
under the terms of the BSD
License.
.Sh AUTHORS
.An -nosplit
Original author:
.An Sebastian Dröge Aq Mt slomo@debian.org
Updates:
.An David Bryant Aq Mt david@wavpack.com
Copyright \(co
2005
Sebastian Dröge Copyright \(co
2017
David Bryant
WavPack
WavPack Executable Programs
5.1.0
