.Dd November 28, 2017
.Dt URLVIEW 1
.Os
.Sh NAME
.Nm urlview
.Nd extract URLs from text
.Sh SYNOPSIS
.Nm
.Ar
.Sh DESCRIPTION
.Nm
is a screen oriented program for extracting URLs from text
and displaying a menu from which you may launch a command
to view a specific item.
.Nm
reads its input from a named
.Ar file
or stdin.
.Pp
Upon startup,
.Nm
attempts to read
.Pa ~/.urlview .
If this file doesn't exist, it will try to read a system wide file in
.Pa /etc/urlview.conf .
Two commands are recognized in the configuration files
(order does not matter):
.Bl -tag -width Ds
.It REGEXP Ar regexp
.Nm
uses a regular expression to extract URLs from the specified text files.
\er, \et, \en and \ef are all converted to their normal
.Xr printf 3
meanings.
The default REGEXP is:
.Bd -literal
(((https?|ftp|gopher)://|(mailto|file|news):)[^' \et<>"]+|(www|web|w3)\e.[-a-z0-9.]+)[^' \et.,;<>"\e):]
.Ed
.It COMMAND Ar command
If the specified command contains
.Dq %s ,
it will be subsituted with the URL that was requested,
otherwise the URL is appended to the COMMAND string.
The default COMMAND is:
.Bd -literal
url_handler.sh %s
.Ed
.El
.Pp
You should never put single quotes around the
.Dq %s .
.Nm
does this for you, and also makes sure that single quotes
eventually showing up inside the URL are handled properly.
(This shouldn't happen with the default regular expression,
which explicitly excludes single quotes.)
.Sh FILES
.Bl -tag -width /etc/urlview.conf -compact
.It Pa /etc/urlview.conf
system-wide configuration file
.It Pa ~/.urlview
user configuration file
.El
.Sh SEE ALSO
.Xr printf 3 ,
.Xr regex 3
.Sh AUTHORS
.An Michael Elkins Aq Mt me@cs.hmc.edu
.An Werner Fink Aq Mt werner@suse.de
.An Stepan Kasal
.An Luis Francisco Gonzalez
.An Thomas Roessler Aq Mt roessler@does-not-exist.org
