.Dd September 20, 2016
.Dt BMFCONV 1
.Os
.Sh NAME
.Nm bmfconv
.Nd convert between bmf databases
.Sh SYNOPSIS
.Nm
.Op Fl d Ar db
.Op Fl f Ar fmt
.Op Fl eihv
.Sh DESCRIPTION
.Nm
converts
.Xr bmf 1
token databases between supported formats.
It can import flat text files into databases
and export databases into flat text files.
The text files used in import and export operations
are read and written in the current directory.
.Pp
The options are as follows:
.Pp
.Bl -tag -width Ds -compact
.It Fl d Ar db
Specify directory or database name.
.It Fl f Ar fmt
Specify database format:
.Dq db
for libdb or
.Dq mysql
for MySQL.
.It Fl e
Export to
.Pa goodlist.txt
and
.Pa spamlist.txt
.It Fl i
Import from
.Pa goodlist.txt
and
.Pa spamlist.txt
.It Fl h
Display a short help.
.It Fl v
Display version information.
.El
.Sh FILES
.Bl -tag -compact -width spamlist.txt
.It Pa goodlist.txt
Text file of good tokens.
.It Pa spamlist.txt
Text file of spam tokens.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
.Dl $ cd ~/.bmf/
.Dl $ bmfconv -e
.Sh SEE ALSO
.Xr bmf 1
.Sh AUTHORS
.An Tom Marshall Aq Mt tommy@tig-grr.com
.Sh BUGS
The import/export file paths are hardcoded.
