.Dd September 19, 2015
.Dt BASE64 1
.Os
.Sh NAME
.Nm base64
.Nd encode and decode data as base64
.Sh SYNOPSIS
.Nm base64
.Op Fl d | e
.Op Fl n
.Op Fl u
.Op Ar infile
.Op Ar outfile
.Sh DESCRIPTION
The MIME (Multipurpose Internet Mail Extensions) specification
(RFC 1341 and successors) defines a mechanism for encoding
arbitrary binary information for transmission by electronic mail.
Triplets of 8-bit octets are encoded as groups of four characters,
each representing 6 bits of the source 24 bits.
Only characters present in all variants of ASCII and EBCDIC are used,
avoiding incompatibilities in other forms of encoding such as
.Xr uuencode 1 .
.Pp
.Nm
is a command line utility which encodes and decodes files in this format.
It can be used within a pipeline as an encoding or decoding filter,
and is most commonly used in this manner as part of an automated
mail processing system.
.Pp
If no
.Ar infile
is specified or
.Ar infile
is a single
.Sq - ,
.Nm
reads from standard input.
If no
.Ar outfile
is given, or
.Ar outfile
is a single
.Sq - ,
.Nm
writes to standard output.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Decode the input.
.It Fl e
Encode the input.
This is the default.
.It Fl n
Suppress error checking when decoding.
By default, upon encountering a non-whitespace character
which does not belong to the base64 set,
or discovering the input file is incorrectly padded
to a multiple of four characters,
.Nm
issues an error message and terminates with exit status 1.
The
.Fl n
option suppresses even this rudimentary error checking;
invalid characters are silently ignored and the output truncated
to the last three valid octets if the input is incorrectly padded.
.It Fl u
Print usage information.
.El
.Sh EXIT STATUS
.Nm
returns status 0 if processing was completed without errors,
1 if an I/O error occurred or errors were detected in decoding a file,
which indicate it is incorrect or incomplete,
and 2 if processing could not be performed at all due,
for example, to a nonexistent input file.
.Sh SEE ALSO
.Xr uuencode 1
.Sh STANDARDS
.Rs
.%A N. Borenstein
.%A N. Freed
.%D June 1992
.%R RFC 1341
.%T Multipurpose Internet Mail Extensions
.Re
.Sh AUTHORS
.An -split
.An John Walker Aq Mt bugs@fourmilab.ch
.An Christian Ferrari Aq Mt Christian.Ferrari@fccrt.it
.Sh BUGS
Little or no error checking is done when decoding,
other than validating that the input consists
of a multiple of four characters in the encoding set.
This is inherent in the design of base64,
which assumes transmission integrity is
the responsibility of a higher-level protocol.
