.Dd Sep 17, 2016
.Dt TOAST 1
.Os
.Sh NAME
.Nm toast
.Nd GSM 06.10 lossy sound compression
.Sh SYNOPSIS
.Nm toast
.Op Fl CcdFfhpv
.Op Fl alsu
.Ar
.Nm untoast
.Op Fl cFfhpv
.Op Fl alsu
.Ar
.Nm tcat
.Op Fl Fhv
.Op Fl alsu
.Ar
.Sh DESCRIPTION
.Nm
compresses the sound files given on its command line.
Each file is replaced by a file with the extension
.Dq gsm .
If no files are specified, the compression is applied to the
standard input, and its result is written to standard output.
.Pp
Toasted files can be restored to something not quite unlike
their original form by running
.Nm toast
.Fl d
or
.Nm untoast
on the
.Dq gsm
files or standard input.
.Pp
The program
.Nm tcat ,
which is the same as
.Nm untoast
.Fl c ,
uncompresses its input on standard output,
but leaves the compressed
.Dq gsm
files alone.
.Pp
When files are compressed or uncompressed into other files,
the access and modification time and access mode is preserved.
.Pp
The options are as follows.
.Bl -tag -width Ds
.It Fl C
Ignore most sample values when calculating
the GSM long-term correlation lag during encoding.
(The multiplications that do this are a bottleneck of the algorithm.)
The resulting encoding process
will not produce exactly the same resultsas GSM 06.10 would,
but remains close enough to be compatible.
The
.Fl C
option applies only to the encoder and is silently ignored by the decoder.
.It Fl c
Write to the standard output; no files are changed.
.It Fl d
Decode, rather than encode, the files.
.It Fl F
On systems with a floating point processor,
but without a multiplication instruction,
.Fl F
sacrifices standard conformance to performance
and nearly doubles the speed of the algorithm.
The resulting encoding and decoding process
will not produce exactly the same results as GSM 06.10 would,
but remains close enough to be compatible.
.It Fl f
Force replacement of output files if they exist.
By default, the user is prompted as to whether the file should be replaced.
.It Fl h
Prints a short overview of the options.
.It Fl p
Do not delete the source files.
Source files are implicitly left alone whenever
.Fl c
is specified or
.Nm tcat
is run.
.It Fl v
Print the version to stdout and exit.
.El
.Pp
.Nm toast ,
.Nm untoast
and
.Nm tcat
try to guess the appropriate audio data format from the filename suffix.
Command line options can also specify a format to be used for all files.
The following formats are supported:
.Bl -tag -width Ds
.It Fl u
\(*m-law: 8 kHz, 8 bit \(*m-law encoding.
Default for
.Dq .u
files.
.It Fl a
A-law: 8 kHz, 8 bit A-law encoding.
Default for
.Dq .a
files.
.It Fl s
sun audio: 8 kHz, 8 bit \(*m-law encoding with an audio header.
Default for
.Dq .au
files.
.It Fl l
linear: 8 kHz, 16 bit signed linear encoding in host byte order
with 13 significant bits.
Default for
.Dq .l
files.
.El
.Pp
In absence of options or suffixes to specify a format,
\(*m-law encoding as forced by
.Fl u
is assumed.
.Sh SEE ALSO
.Xr gsm 3
.Sh AUTHORS
.An Jutta Degener Aq Mt jutta@panix.com
.An Carsten Bormann
.Sh CAVEATS
A four bit magic number is prefixed to each 32 1/2-byte GSM frame,
mainly because 32 1/2-bytes are rather clumsy to handle.
.Pp
The compression algorithm used is a lossy compression algorithm
devised especially for speech; on no account should it be used
for text, pictures or any other non-speech-data you consider valuable.
