.Dd January 12, 2023
.Dt TOAST 1
.Os
.Sh NAME
.Nm toast
.Nd GSM 06.10 lossy sound compression
.Sh SYNOPSIS
.Nm toast
.Op Fl cdfpCFvhuasl
.Ar
.Nm untoast
.Op Fl cfpFhvuasl
.Ar
.Nm tcat
.Op Fl Fhvuasl
.Ar
.Sh DESCRIPTION
Toast compresses the sound files given on its command line.
Each file is replaced by a file with a
.Dq .gsm
extension.
If no files are specified, the compression is applied to
standard input, and its result is written to standard output.
.Pp
Toasted files can be restored to something not quite unlike
their original form by running
.Nm toast Fl d
or
.Nm untoast .
The
.Nm tcat
program, which is the same as as running
.Nm untoast Fl c ,
uncompresses its input to standard output,
but leaves the compressed gsm files alone.
.Pp
When files are compressed or uncompressed into other files,
the ownership (if run by root), modes, access and modification times
are maintained.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
(cat)
Write to the standard output; no files are changed.
.It Fl d
(decode)
Decode, rather than encode, the files.
.It Fl f
(force)
Force replacement of output files if they exist.
.It Fl p
(precious)
Do not delete the source files.
Source files are left alone whenever
.Fl c
is specified or
.Nm tcat
is run.
.It Fl C
(LTP cut-off)
Ignore most sample values when calculating the
GSM long-term correlation lag during encoding.
(The multiplications that do this are a bottleneck of the algorithm.)
The resulting encoding process will not produce
exactly the same results as GSM 06.10 would,
but remains close enough to be compatible.
.It Fl F
(fast)
On systems with a floating point processor,
but without a multiplication instruction,
.Fl F
sacrifices standard conformance to performance
and nearly doubles the speed of the algorithm.
The resulting encoding and decoding process will not produce
exactly the same results as GSM 06.10 would,
but remains close enough to be compatible.
.It Fl h
(help) prints a short overview of the options.
.It Fl v
(version) outputs the version number to stdout and exits.
.El
.Pp
.Nm toast ,
.Nm untoast
and
.Nm tcat
try to guess the appropriate audio data format from the file suffix.
Command line options can also specify a format to be used for all files.
The following formats are supported:
.Bl -tag -width Ds
.It Fl u
(\(*m-law) 8 kHz, 8 bit \(*mU-law encoding
.Pq suffix Dq .u
.It Fl a
(A-law) 8 kHz, 8 bit A-law encoding
.Pq Dq .A
.It Fl s
(Sun audio) 8 kHz, 8 bit \(*m-law encoding with audio header
.Pq Dq .au
.It Fl l
(linear) 8 kHz, 16 bit signed linear encoding in host byte order
with 13 significant bits
.Pq Dq .l
.El
.Pp
In the absence of options or suffixes to specify a format,
\(*m-law encoding as forced by
.Fl u
is assumed.
.Sh SEE ALSO
.Xr gsm 3
.Sh AUTHORS
.An Jutta Degener Aq Mt jutta@pobox.com
.An Carsten Bormann Aq Mt cabo@tzi.org
.Sh CAVEATS
A four bit magic number is prefixed to each 32-and-half-byte GSM frame,
mainly because 32-and-half-bytes are rather clumsy to handle.
