.Dd January 29, 2018
.Dt OPUSDEC 1
.Os
.Sh NAME
.Nm opusdec
.Nd decode Opus audio
.Sh SYNOPSIS
.Nm
.Op Fl hV
.Op Fl -quiet
.Op Fl -rate Ar Hz
.Op Fl -gain Ar dB
.Op Fl -no-dither
.Op Fl -float
.Op Fl -force-wav
.Op Fl -packet-loss Ar pct
.Op Fl -save-range Ar file
.Ar input.opus
.Op Ar output.wav
.Sh DESCRIPTION
.Nm
decodes Opus files into PCM wave files.
An input file named
.Sq -
means
.Nm
will read from stdin.
Likewise, an output filename of
.Sq -
will cause output to be written to stdout.
If no output file is specified,
.Nm
will attempt to play the audio in realtime
if it supports audio playback on your system.
.Pp
The options are as follows:
.Pp
.Bl -tag -compact -width --save-range-file
.It Fl h Fl -help
Print a help message and exit
.It Fl V Fl -version
Display version information and exit.
.It Fl -quiet
Suppress program output.
.It Fl -rate Ar Hz
Force decoding at the specified sampling rate.
.It Fl -gain Ar dB
Adjust the output volume by the specified amount.
.It Fl -no-dither
Do not dither 16-bit output.
.It Fl -float
Write 32-bit floating-point output.
.It Fl -force-wav
Force including a wav header in output (even stdout).
.It Fl -packet-loss Ar pct
Simulate the specified random Opus packet loss.
.It Fl -save-range Ar file
Saves values of every frame to the specified
.Ar file .
.El
.Sh EXAMPLES
Decode
.Pa input.opus
to
.Pa output.wav :
.Dl opusdec input.opus output.wav
.Pp
Play
.Pa input.opus
at 48000 Hz regardless of the original sampling rate:
.Dl opusdec --rate 48000 input.opus
.Pp
Re-encode a high bitrate Opus file to a lower rate:
.Dl opusdec --force-wav input.opus - | opusenc --bitrate 64 - output.opus
.Pp
Play a http stream with the help of curl on a system with pulseaudio:
.Dl curl http://icecast.somwhere.org:8000/stream.opus | padsp opusdec -
.Sh SEE ALSO
.Xr opusenc 1 ,
.Xr opusinfo 1
.Sh AUTHORS
.An Jean-Marc Valin Aq Mt jmvalin@jmvalin.ca
.An Gregory Maxwell Aq Mt greg@xiph.org
.Sh BUGS
Opusdec does not currently reject
all invalid files which it should reject.
It also doesn't provide very helpful output
for the corrupted files it does reject.
Use
.Xr opusinfo 1
for somewhat better diagnostics.
