.Dd December 7, 2017
.Dt OPUSRTP 1
.Os
.Sh NAME
.Nm opusrtp
.Nd encapsulate Opus audio in RTP
.Sh SYNOPSIS
.Nm
.Op Fl hV
.Op Fl -sniff
.Ar
.Sh DESCRIPTION
Demonstration tool for sending and receiving Opus audio data in RTP,
used for interactive applications on the internet.
By default, Opus audio from each given file is sent as an RTP stream.
.Pp
The options are as follows
.Bl -tag -width Ds
.It Fl h , -help
Print help message
.It Fl V , --version
Display version information
.It Fl -quiet
Suppresses program output
.It Fl -sniff
Sniff the network for active RTP sessions and save them to .opus files.
This can be useful for debugging other Opus RTP implementations.
For this function to work, the program must be run with superuser privileges.
.El
.Sh SEE ALSO
.Xr opusdec 1 ,
.Xr opusenc 1 ,
.Xr opusinfo 1
.Sh AUTHORS
.An Ralph Giles Aq Mt giles@thaumas.net
.Sh BUGS
Only the sniff mode is implemented;
the tool should do normal unicast and multicast send/receive.
The sniff mode should allow specifying
device, host, port, payload type to limit capture.
All that is hard-coded.
