.Dd November 9, 2020
.Dt EXPLICATEUTF8 1
.Os
.Sh NAME
.Nm ExplicateUTF8
.Nd explain a sequence of bytes as a UTF8 encoding
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl o Ar offset
.Op Ar file
.Sh DESCRIPTION
.Nm
examines its input and determines whether
it begins with a valid UTF8 Unicode sequence.
If the sequence is invalid, it explains why.
If the sequence is valid, it explains why,
gives the equivalent UTF-32 code,
and explains how this value was computed.
If no input file is supplied,
.Nm
reads from the standard input.
.Pp
The options are as follows:
.Pp
.Bl -tag -width "offsetXXX" -compact
.It Fl h
Print the usage message and exit.
.It Fl o Ar offset
Skip the first
.Ar offset
bytes of input.
.It Fl v
Print version information and exit.
.El
.Sh STANDARDS
Unicode Standard, version 4.1
.Sh AUTHORS
.An Bill Poser Aq Mt billposer@alum.mit.edu
