.Dd November 9, 2020
.Dt UNIDESC 1
.Os
.Sh NAME
.Nm unidesc
.Nd describe the contents of a Unicode text file
.Sh SYNOPSIS
.Nm
.Op Fl bdhLlmpruvw
.Ar file
.Sh DESCRIPTION
.Nm
reads the given
.Ar file
(or standard input if no file is given)
and describes its Unicode content by reporting the character ranges
to which different portions of the text belong.
The ranges reported include both official Unicode ranges
and the constructed language ranges within the Private Use Areas
registered with the Conscript Unicode Registry
(see http://www.evertype.com/standards/csur/).
For each range of characters,
.Nm
prints the character or byte offset of the beginning of the range,
the character or byte offset of the end of the range,
and the name of the range.
Offsets start from 0.
.Pp
Since the ASCII digits, punctuation, and whitespace characters
are frequently used by other writing systems,
these characters are by default treated as neutral, that is,
as not belonging exclusively to any particular character range.
These characters are treated as belonging to
the range of whatever characters precede them.
If the input begins with neutral characters, they are treated
as belonging to the range of whatever characters follow them.
If the file consists entirely of neutral characters,
the range is identified as
.Dq Neutral [Basic Latin] .
.Pp
A magic number identifying the Unicode encoding
is not part of the Unicode standard,
so pure Unicode files do not contain a magic number.
However, informal conventions have arisen for this purpose.
If the
.Fl m
option is given,
.Nm
will attempt to identify the Unicode subtype
by examining the first few bytes of the input.
If the input is identified as one of the two acceptable types,
UTF-8 or native order UTF-32, it will then proceed
to describe the contents of the input.
Otherwise, it will report what it has learned and exit.
Note that if the file does contain a magic number,
you must use the
.Fl m
option.
Without this flag,
.Nm
assumes that the input consists of pure Unicode
with the character data beginning immediately,
and will therefore be thrown off by the magic number.
.Nm
By default, input is expected to be UTF-8.
Native order UTF-32 is also acceptable,
and may be specified via the
.Fl u
option, or the
.Fl m
option via the magic number.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl b
Give file offsets in bytes rather than characters.
.It Fl d
Treat the ASCII digits as belonging exclusively to the Basic Latin range.
.It Fl h
Print usage information and exit.
.It Fl L
List the Unicode ranges alphabetically.
.It Fl l
List the Unicode ranges by codepoint.
.It Fl m
Check the file's magic number to determine the Unicode subtype.
.It Fl p
Treat ASCII punctuation as belonging exclusively to the Basic Latin range.
.It Fl r
Instead of listing ranges as they are encountered,
just list the ranges detected after all input has been read.
.It Fl u
Input is native order UTF-32.
.It Fl v
Print version information.
.It Fl w
Treat ASCII whitespace as belonging exclusively to the Basic Latin range.
.El
.Sh SEE ALSO
.Xr uniname 1
.Sh STANDARDS
Unicode Standard, version 5.0
.Sh AUTHORS
.An Bill Poser Aq Mt billposer@alum.mit.edu
