.Dd November 13, 2020
.Dt UNIFUZZ 1
.Os
.Sh NAME
.Nm unifuzz
.Nd emit strings designed to test Unicode handling
.Sh SYNOPSIS
.Nm
.Op Fl bghlnqSuv
.Op Fl r Ar number
.Op Fl s Ar seed
.Sh DESCRIPTION
.Nm
emits strings designed to test the ability of programs
intended to accept Unicode input to handle unexpected input.
These include: characters from all Unicode ranges, Private Use characters,
surrogates, undefined characters, non-characters, control characters,
exotic space characters, sequences violating normalization rules,
unexpected sequences (e.g. a base character from one range
followed by a combining character from another range),
and long sequences of combining characters.
It can also generate very long lines,
strings containing embedded nulls, and ill-formed UTF-8.
.Pp
.Nm
also emits a sequence of random characters (1 million by default)
determined by a pseudorandom number generator.
The same sequence can be obtained by setting the
.Ar seed
to the same value using the
.Fl s
option.
If not set on the command line,
a seed is chosen based on the time of execution.
The seed used is included in the output in a line of the form
.Dq Seed = NNNNNN
immediately preceding the output character sequence.
Note that in order to obtain the same output sequence
it is necessary to also keep the same BMP restriction using the
.Fl b
option.
.Pp
The options are as follows:
.Pp
.Bl -tag -width "numberXXX" -compact
.It Fl b
Restrict the output to the Basic Multilingual Plane (Plane 0).
.It Fl g
Do not emit specific characters.
.It Fl h
Print usage information and exit.
.It Fl l
Emit very long lines.
.It Fl n
Emit strings with embedded nulls.
.It Fl q
Be quiet: omit commentary.
.It Fl r Ar number
Set the
.Ar number
of random characters to emit.
.It Fl S
Scan ranges: emit a character from each range.
.It Fl s Ar seed
Set the seed for the random number generator.
.It Fl u
Emit ill-formed UTF-8 as well.
.It Fl v
Print version information and exit.
.El
.Sh STANDARDS
Unicode Standard, version 5.0
.Sh AUTHORS
.An Bill Poser Aq Mt billposer@alum.mit.edu
