.Dd November 9, 2020
.Dt UNIHIST 1
.Os
.Sh NAME
.Nm unihist
.Nd generate a histogram of characters in a Unicode file
.Sh SYNOPSIS
.Nm
.Op Fl cghuv
.Sh DESCRIPTION
.Nm
generates a histogram of the characters in its input,
which must be encoded in UTF-8 Unicode.
By default, for each character, it prints the frequency
of the character as a percentage of the total,
the absolute number of tokens in the input,
the UTF-32 code in hexadecimal, and,
if the character is displayable, the glyph itself as UTF-8 Unicode.
Command line flags allow some of this information to be suppressed.
In particular, by suppressing the percentages and counts
it is possible to generate a list of the unique characters in the input.
.Pp
The output is ordered by character code.
To sort it in descending order of frequency,
pipe the output into
.Xr sort 1 .
.Pp
By default,
.Nm
handles all of Unicode.
To reduce memory usage and increase speed, it may be compiled
so as to handle only the Basic Multilingual Plane (plane 0)
by defining BMPONLY.
.Pp
The options are as follows:
.Pp
.Bl -tag -width Ds -compact
.It Fl c
Suppress printing of counts and percentages.
.It Fl g
Suppress printing of glyphs.
.It Fl h
Print usage information and exit.
.It Fl u
Suppress printing of the Unicode code as text.
.It Fl v
Print version information and exit.
.El
.Sh SEE ALSO
.Xr uniname 1
.Sh STANDARDS
Unicode Standard, version 5.0
.Sh AUTHORS
.An Bill Poser Aq Mt billposer@alum.mit.edu
