.Dd November 9, 2020
.Dt UNINAME 1
.Os
.Sh NAME
.Nm uniname
.Nd name the characters in a Unicode text file
.Sh SYNOPSIS
.Nm
.Op Fl AaBbceghlnpqruVv
.Op Fl S Ar offset
.Op Fl s Ar offset
.Ar file
.Sh DESCRIPTION
.Nm
reads the input
.Ar file
(or the standard input if no file is given)
and for each character it prints the character offset,
the byte offset, the hexadecimal UTF-32 character code,
the encoding as a sequence of hex byte values, the glyph,
and the character's Unicode name.
Command line flags allow for some of this information to be suppressed.
Glyphs that do not display nicely, such as control characters and spaces,
are not displayed.
For the Latin-1 control characters
(whose official Unicode name is
.Dq control )
the real name is given.
Character and byte offsets both start from 0.
.Pp
Where a character does not have a unique Unicode name,
as is the case with Chinese characters,
the character is identified as
.Dq character in such-and-such range .
However, if the character is a Chinese character
listed in Nelson's dictionary, the Nelson number is supplied.
.Pp
By default, input is expected to be UTF-8.
Native order UTF-32 may be specified via the
.Fl q
option.
If invalid UTF8 is encountered,
an explanation is printed as to why it is invalid.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A
Skip ASCII whitespace characters.
.It Fl a
Skip ASCII characters.
.It Fl B
Skip characters within the Basic Multilingual Plane.
.It Fl b
Don't print the byte offset.
.It Fl c
Don't print the character offset.
.It Fl e
Don't print the encoding.
.It Fl g
Don't print the glyph.
.It Fl h
Print usage information and exit.
.It Fl l
Print the line number.
.It Fl n
Don't print the Unicode name.
.It Fl p
Don't print the headers every screenfull.
.It Fl q
Input is native order UTF-32.
.It Fl r
Print Unicode range.
The ranges reported include both official Unicode ranges
and the constructed language ranges within the Private Use Areas
registered with the Conscript Unicode Registry (see
http://www.evertype.com/standards/csur/).
.It Fl S Ar offset
Skip
.Ar offset
many bytes.
Note that even if the file consists of well-formed Unicode
there is no guarantee that the byte sequence beginning at
an arbitrary byte offset will be valid Unicode.
This option is provided for use where other programs generate
only byte offsets or where it is necessary to skip over damaged Unicode.
In most circumstances the use of a character offset
will be more apprpriate (see the
.Fl s
option).
If a byte offset is used, the character offsets shown are relative to
.Ar offset
rather than the beginning of the file.
.It Fl s Ar offset
Skip
.Ar offset
many characters.
.It Fl u
Don't print the UTF32 code.
.It Fl V
Validate the input.
.Nm
will merely determine whether the input is valid UTF-8 Unicode.
If it is, no output is produced and the program exits with status 0.
If invalid UTF-8 is encountered, the program reports the location
of the first invalid UTF-8 encountered, explains why it is invalid,
and exits with status 1.
.It Fl v
Print version information and exit.
.El
.Sh SEE ALSO
.Xr unidesc 1
.Sh STANDARDS
Unicode Standard, version 5.1
.Sh AUTHORS
.An Bill Poser Aq Mt billposer@alum.mit.edu
