.Dd June 16, 2023
.Dt DIFFPP 1
.Os
.Sh NAME
.Nm diffpp
.Nd pretty-print diffs using enscript
.Sh SYNOPSIS
.Nm
.Ar original
<
.Ar diff
.Sh DESCRIPTION
.Nm
converts the output of
.Xr diff 1
into a format suitable for
.Xr enscript 1 .
.Nm
annotates the changes with enscript's special escapes
so enscript can highlight the modified portions of the file.
The changed and added lines are printed with gray-background,
deleted lines are marked with minus characters.
.Sh EXAMPLES
The easiest way to use
.Nm
is to use it as an input filter for enscript,
preprocessing its incoming data stream.
The filtering does not alter any header strings or file timestamps
which might get printed in enscript headers;
only the incoming data is modified.
.Pp
Print the diffs between source files and their backups:
.Dl enscript -G2re --filter='diff %s~ %s | diffpp %s' *.c *.h
.Pp
Print the git diffs of source files:
.Dl enscript -G2re --filter='git diff %s | diffpp %s' *.c *.h
.Sh SEE ALSO
.Xr diff 1 ,
.Xr enscript 1
.Sh AUTHORS
.An Markku Rossi Aq Mt mtr@iki.fi
